services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: client
    volumes:
      - ./client/:/app/client
      - /app/client/node_modules
    ports:
      - "5173:5173"
    environment:
      - SERVER_URL=http://server:8000
  
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: server
    volumes:
      - ./server:/app/server
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000